### ISSUE TITLE
please specify the required version of transformers lib

### ISSUE THREAD

**Issue by kwonmha** [CPJKU/wechsel#5]
I used older version and had hard time making `train_new_from_iterator()` work.

TY

**Comment by bminixhofer** [comment]
Hi! Thanks, good catch, and sorry for the inconvenience. 

In https://github.com/CPJKU/wechsel/commit/540c43eeed072bc9fc0b59a836711af8c8af3b2e I've added `transformers` and `tokenizers` versions to the `requirements.txt`, previously it slipped through because the library itself does not use them (they're only used in the examples).

**Comment by kwonmha** [comment]
It was a really fast reply!
Thank you.
